language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

env:
    global:
        # GH_TOKEN define in repository settings on travis-ci.org
        - GH_REPO: github.com/locomotivemtl/charcoal-coding-standard.git

matrix:
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer self-update --quiet

install:
    - composer install --no-interaction --no-suggest
    # - composer add-standard
    - mkdir -p build/logs/

script:
    - composer test-checks
    - composer test-fixes
    # - composer test-sniffs -- --coverage-clover "build/logs/clover.xml"

notifications:
    slack: locomotivemtl:d9h8ZWwTZ6b3WUsSP9s26nb1
    email: charcoal@locomotive.ca
