<?php
/**
 * TODO: Write this comment
 * TODO
 */

/** @todo remove this. */
error_log('test');

// TODO: remove this.
Debug::bam('test');

// todo - remove this.

// Extract info from the array.
// TODO: can this be done faster?

// Extract info from the array (todo: make it faster)
// To do this, use a function!
// notodo! NOTODO! NOtodo!
//TODO.
//étodo
//todoé

/** @todo:hack This is not how we should do this. */
